---
title: "enseml_SVs"
author: "Jenny Jakobsson"
date: "4/19/2021"
output: html_document

params:
  workingDir: '~/breedmaps/SVs_identification/'
  functions: 'scripts/gene_annotation/functions.R'
  annDir: 'data/annotation/'
  ensembl_svs: 'bos_taurus_structural_variations.gvf'
  resultsDir: 'results/gene_annotation/filtered_variants/'
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(GenomicRanges)

source(paste(params$workingDir, params$functions, sep=""))
```

## ENSEMBL SVs
Downloaded from http://ftp.ensembl.org/pub/release-103/variation/gvf/bos_taurus/bos_taurus_structural_variations.gvf.gz 19/4-21. Source = DGVa, database of  genomic variants archive (https://www.ebi.ac.uk/dgva/)

```{r }
path = paste(params$workingDir,
             params$annDir,
             params$ensembl_svs,
             sep = "")
ensembl_svs = read.table(
  file = path,
  quote = "",
  sep = "\t",
  header = F,
  stringsAsFactors = F
)
ensembl_svs = ensembl_svs %>% dplyr::rename(
  ENSEMBL_CHROM = V1,
  ENSEMBL_SOURCE = V2,
  ENSEMBL_SV_TYPE = V3,
  ENSEMBL_START = V4,
  ENSEMBL_END = V5,
  Empty1 = V6,
  ENSEMBL_STRAND = V7,
  Empty2 = V8,
  ENSEMBL_INFO = V9
)
ensembl_cleaned = ensembl_svs %>% dplyr::select(ENSEMBL_CHROM, ENSEMBL_START, ENSEMBL_END, ENSEMBL_STRAND, ENSEMBL_SOURCE, ENSEMBL_INFO) %>% dplyr::distinct(ENSEMBL_CHROM, ENSEMBL_START, ENSEMBL_END)

ensembl_range = makeGRangesFromDataFrame(
  ensembl_cleaned,
  seqnames.field = "ENSEMBL_CHROM",
  start.field = "ENSEMBL_START",
  end.field = "ENSEMBL_END",
  strand.field = "ENSEMBL_STRAND"
)
```



```{r}
path = paste(params$workingDir,
             params$resultsDir,
             sep = "")
gene_file_names = list.files(path = path, pattern = "filt_ann_gene*")

overlap_list = list()
for (i in 1:(length(gene_file_names)/2-0.5)) {
  full_path = paste(params$workingDir,
                    params$resultsDir,
                    gene_file_names[[i]],
                    sep = "")
  svs = read.table(
    file = full_path,
    quote = "",
    sep = "\t",
    header = T,
    stringsAsFactors = F
  ) %>% dplyr::rename(SV_CHROM = CHROM,
                      SV_START = POS,
                      SV_END = END)
  svs = svs %>% dplyr::filter(SV_LENGTH < 50000000) %>% dplyr::rename(ID1 = ID)
  sv_range = makeGRangesFromDataFrame(
    svs,
    seqnames.field = "SV_CHROM",
    start.field = "SV_START",
    end.field = "SV_END",
  )
  ensembl_cleaned$ID2 = rownames(ensembl_cleaned)
  overlap = findoverlap_dataframe(sv_range, ensembl_range, svs, ensembl_cleaned)
  #sv_range = ID1, ensembl = ID2
  overlap_list[[i]] = overlap %>% dplyr::rename(SV_ID = ID1) %>% dplyr::select(-ID2)
  filt_results = paste(
    params$workingDir,
    "results/",
    "gene_annotation/",
    "ensembl_ann/",
    "ensembl_",
    gene_file_names[[i]],
    sep = ""
  )
  write.table(
    x = overlap_list[[i]],
    file = filt_results,
    quote = F,
    sep = "\t",
    row.names = F,
    col.names = T
  )
}

```

```{r}
for (i in (length(gene_file_names)/2+0.5):(length(gene_file_names))) {
  full_path = paste(params$workingDir,
                    params$resultsDir,
                    gene_file_names[[i]],
                    sep = "")
  svs = read.table(
    file = full_path,
    quote = "",
    sep = "\t",
    header = T,
    stringsAsFactors = F
  ) %>% dplyr::rename(SV_CHROM = CHROM,
                      SV_START = POS,
                      SV_END = END)
  svs = svs %>% dplyr::filter(SV_LENGTH < 50000000) %>% dplyr::rename(ID1 = ID)
  sv_range = makeGRangesFromDataFrame(
    svs,
    seqnames.field = "SV_CHROM",
    start.field = "SV_START",
    end.field = "SV_END",
  )
  ensembl_cleaned$ID2 = rownames(ensembl_cleaned)
  overlap = findoverlap_dataframe(sv_range, ensembl_range, svs, ensembl_cleaned)
  #sv_range = ID1, ensembl = ID2
  overlap_list[[i]] = overlap %>% dplyr::rename(SV_ID = ID1) %>% dplyr::select(-ID2)
  filt_results = paste(
    params$workingDir,
    "results/",
    "gene_annotation/",
    "ensembl_ann/",
    "ensembl_",
    gene_file_names[[i]],
    sep = ""
  )
  write.table(
    x = overlap_list[[i]],
    file = filt_results,
    quote = F,
    sep = "\t",
    row.names = F,
    col.names = T
  )
}
# for(i in 1:length(overlap_list)){
# filt_results = paste(
#     params$workingDir,
#     "results/",
#     "ensembl_ann/",
#     "ensembl_",
#     gene_file_names[[i]],
#     ".tsv",
#     sep = ""
#   )
#   write.table(
#     x = overlap_list[[i]],
#     file = filt_results,
#     quote = F,
#     sep = "\t",
#     row.names = F,
#     col.names = T
#   )
# }
```


